FROM node:16-alpine as base

WORKDIR /app

COPY package.json ./

COPY yarn.lock ./

COPY tsconfig.json ./

COPY src ./src

RUN yarn

RUN yarn build


FROM base as production

WORKDIR /app

COPY package.json ./

RUN yarn --only=production

COPY --from=0 /app/dist .

# RUN yarn add pm2 -g

EXPOSE 5000

CMD ["yarn","start"]